### ISSUE TITLE
Giving page doesn't have FPS QR Code

### ISSUE THREAD

**Issue by andreajeka** [hmcc-global/hmcchk-web#150]
Need this up if we wanna see our church grow in tithing. I think we can put the QR Code inside the pop up after clicking "Learn More"

![image](https://user-images.githubusercontent.com/8019899/150458001-dfe49bb6-3cf7-4c07-8d8e-e82e4827d7e3.png)

![image](https://user-images.githubusercontent.com/8019899/150457963-a04b7dcc-8191-425b-8ea0-1e8630c49afa.png)

**Comment by ksuhartono97** [comment]
The QR code is supposed to be there. Issue is caused by #149 that all images in this page is currently not loading
