### ISSUE TITLE
Next session/Live card

### ISSUE THREAD

**Issue by albertparedandan** [hmcc-global/hmcchk-web#191]

**Comment by samyakobus** [comment]
Seems alright

at 7:29 PM still coming
![image](https://user-images.githubusercontent.com/33675629/155552482-77a3af01-5d74-4f68-a5a4-3ee9f00355a2.png)

at 7:30 PM live
![image](https://user-images.githubusercontent.com/33675629/155552629-3726697f-c29f-44c8-9ef5-bfae92ef4c0d.png)
