### ISSUE TITLE
Praise wall UI

### ISSUE THREAD

**Issue by albertparedandan** [hmcc-global/hmcchk-web#192]

**Comment by albertparedandan** [comment]
- Create a MongoDB model for praises
  - Name (autofill from loggedin users)
  - Message
  - time submitted
  - category (with-everything-retreat)
- Submitted praises must go through a profanity filter

**Comment by bhryck** [comment]
profanity filter library already  exists: https://npm.io/package/bad-words

**Comment by albertparedandan** [comment]
50% done with UI,
backend 60% done

**Comment by albertparedandan** [comment]
basically done, little bugs to fix
