### ISSUE TITLE
'add to calendar' feature within events should add time in HKT

### ISSUE THREAD

**Issue by kmalvin** [hmcc-global/hmcchk-web#209]
when i click on the 'add to calendar' button for an event card, it prompts a new gcal event to be created, but the time set within the announcement (eg. 1:30PM) is formatted as GMT, and so when my gcal opens, it gets converted into HKT, which is GMT+8 (eg. 930PM)

please change the logic so that it immediately adds the event time stated in the card already as HKT

**Comment by albertparedandan** [comment]
resolved by changing the server's local time zone
