### ISSUE TITLE
Fonts on homepage for buttons are wrong

### ISSUE THREAD

**Issue by cindy-hui** [hmcc-global/hmcchk-web#235]
current:
<img width="888" alt="image" src="https://user-images.githubusercontent.com/97814802/155348888-06992963-5dba-4f8d-a36e-9473a4a5258d.png">

the font should be **Sora** 
design: 
<img width="610" alt="image" src="https://user-images.githubusercontent.com/97814802/155349415-b0ab021e-a2be-4b02-9d41-8bb0bd122a6d.png">

**Comment by ksuhartono97** [comment]
fixed with 0cd4339e4d1f240dec176cfea8426f559a7ffda7

**Comment by cindy-hui** [comment]
"SCHEDULE" and "PRAISE WALL" font should also be Sora
