### ISSUE TITLE
fix the alignment on praise wall header

### ISSUE THREAD

**Issue by cindy-hui** [hmcc-global/hmcchk-web#236]
- the alignment looks off on the current header of the praise wall → too high (?

alignment (current): 
<img width="611" alt="image" src="https://user-images.githubusercontent.com/97814802/155350870-f10acdae-3ab6-465a-871c-a4f5cbfeaade.png">

alignment (design): 
<img width="593" alt="image" src="https://user-images.githubusercontent.com/97814802/155351061-5f49c1dc-d01d-4d06-ba9a-4baba5fd6c8b.png">

**Comment by ksuhartono97** [comment]
fixed with 0cf7fd837cfb692065ac5d2348f254f71dc56f72
