### ISSUE TITLE
Font size of PRAISE WALL should be the same as CWC2022 and Schedule

### ISSUE THREAD

**Issue by cindy-hui** [hmcc-global/hmcchk-web#237]
- the font size of "PRAISE WALL" should be the same as the font size of "SCHEDULE" & "CHURCH-WIDE CONFERENCE 2022"
current:
<img width="772" alt="image" src="https://user-images.githubusercontent.com/97814802/155351451-3e04ca06-08fb-4e55-a4cc-d9f954e0adb0.png">

design:
<img width="963" alt="image" src="https://user-images.githubusercontent.com/97814802/155351337-ed08215a-9cfb-4175-95dc-9344e1169d54.png">

**Comment by ksuhartono97** [comment]
fixed with 0cf7fd837cfb692065ac5d2348f254f71dc56f72
