### ISSUE TITLE
shorten the frame of schedule on web

### ISSUE THREAD

**Issue by cindy-hui** [hmcc-global/hmcchk-web#238]
can the schedule be shorter on the web to align with the block on the left hand side? cus now theres a space between praise wall and the stream info. a bit awkward. If this affects the mobile view we can also shorten it on the mobile pop up.
current:
<img width="828" alt="image" src="https://user-images.githubusercontent.com/97814802/155352159-2e5d54bd-8945-41f6-922c-60866a34c28e.png">

design:
<img width="969" alt="image" src="https://user-images.githubusercontent.com/97814802/155352445-2a5e6341-e76c-4f1d-9d99-0a1353347bc5.png">

**Comment by ksuhartono97** [comment]
fixed with 
57516fd
