### ISSUE TITLE
Resource Page title fixes 

### ISSUE THREAD

**Issue by cindy-hui** [hmcc-global/hmcchk-web#239]
- make font size the same as "SCHEDULE" and "CWC2022" on the homepage
- make the icon bigger too? hahaa
- bold the headers too 
- THIS PAGE looks fire tam 👍 

current: 
<img width="852" alt="image" src="https://user-images.githubusercontent.com/97814802/155353515-a40a3eb3-995d-4ded-976f-e6336d42092b.png">

design:
<img width="633" alt="image" src="https://user-images.githubusercontent.com/97814802/155353736-9f090f44-40b3-4998-936e-cddfcb2b37f0.png">

**Comment by ksuhartono97** [comment]
font is already max bold level but for some reason looks thinner than on Figma, not exactly sure if there's a font problem here

**Comment by ksuhartono97** [comment]
attempted fix with 57516fd
