### ISSUE TITLE
Resources page Mobile view is squished

### ISSUE THREAD

**Issue by cindy-hui** [hmcc-global/hmcchk-web#240]
can make the content wider on the mobile, closer to the edge

current:
![WhatsApp Image 2022-02-23 at 11 45 34 PM](https://user-images.githubusercontent.com/97814802/155354645-dc24fc56-c966-405e-ba6d-35691d76daea.jpeg)

<img width="293" alt="image" src="https://user-images.githubusercontent.com/97814802/155354909-375b2773-a21d-4d61-863f-44f6853eed26.png">

**Comment by ksuhartono97** [comment]
fixed with 57516fd
