### ISSUE TITLE
Add "With Everything" footer on Resources Page

### ISSUE THREAD

**Issue by samyakobus** [hmcc-global/hmcchk-web#242]
Can try to add on right side down

![image](https://user-images.githubusercontent.com/33675629/155366670-748f069c-0e2c-41d9-81ff-85c7a63235f6.png)

**Comment by cindy-hui** [comment]
the final design doesnt have this, its ok
<img width="722" alt="image" src="https://user-images.githubusercontent.com/97814802/155458495-f8a3c539-30b5-4f3e-ab68-9e753c16d9ee.png">
