### ISSUE TITLE
Background

### ISSUE THREAD

**Issue by bhryck** [hmcc-global/hmcchk-web#272]
This refers to the entire background for the whole Easter page, not limited to a particular section

**Comment by bhryck** [comment]
Ensure that the background looks okay as other components get added

**Comment by albertparedandan** [comment]
![Screenshot 2022-03-07 at 20 34 11](https://user-images.githubusercontent.com/33679483/157035340-a283db46-a191-4f97-8898-9124253c5ba9.png)

**Comment by albertparedandan** [comment]
this whole background (NOT the text/image components)
