### ISSUE TITLE
Story section

### ISSUE THREAD

**Issue by bhryck** [hmcc-global/hmcchk-web#274]

**Comment by bhryck** [comment]
the 4 texts and images 
gif of the because__

**Comment by albertparedandan** [comment]
![Screenshot 2022-03-07 at 20 31 03](https://user-images.githubusercontent.com/33679483/157034900-8ab99a0a-ce64-4939-80e3-867f5abfeab2.png)

**Comment by bhryck** [comment]
the because Jesus loves, etc  blue and yellow gif part is now part of issue #275
