### ISSUE TITLE
Because Jesus part

### ISSUE THREAD

**Issue by bhryck** [hmcc-global/hmcchk-web#275]
Research from CXO lol
fade in effect for story section:
• https://www.react-reveal.com
• https://codesandbox.io/s/5z3x61qqxk

because, jesus & cross part:
• add scroll to parallax: https://bestofreactjs.com/repo/keske-react-parallax-component-react-ui-animation
• https://levelup.gitconnected.com/how-to-create-frame-by-frame-moving-image-on-scroll-effect-30ce577c63c2
• https://codepen.io/josephwong2004/pen/wvKPGEO

**Comment by bhryck** [comment]
Ideally have it fade in and parallax scoring, but for minimum just fade in should be ok

**Comment by albertparedandan** [comment]
![Screenshot 2022-03-07 at 20 33 35](https://user-images.githubusercontent.com/33679483/157035258-57caf572-f459-4bf0-811e-488540eb7210.png)

**Comment by bhryck** [comment]
this issue now includes the because jesus blue and yellow gif
![Capture](https://user-images.githubusercontent.com/24607458/158183467-00ea2b22-26c3-49ae-ba7c-2c29d04bf4d1.PNG)
