### ISSUE TITLE
Invitation section

### ISSUE THREAD

**Issue by bhryck** [hmcc-global/hmcchk-web#277]

**Comment by bhryck** [comment]
make the invite images download links

**Comment by albertparedandan** [comment]
![Screenshot 2022-03-07 at 20 32 00](https://user-images.githubusercontent.com/33679483/157035034-65089213-4792-4de2-9a81-39be873d6c99.png)

**Comment by cindy-hui** [comment]
<img width="807" alt="image" src="https://user-images.githubusercontent.com/97814802/157700081-955a8aa4-3574-47c7-93bb-9e425806f2b0.png">
update! - can ask @kmalvin for more details
