### ISSUE TITLE
Hover button behaviour

### ISSUE THREAD

**Issue by albertparedandan** [hmcc-global/hmcchk-web#280]

**Comment by cindy-hui** [comment]
<img width="698" alt="image" src="https://user-images.githubusercontent.com/97814802/157656837-7cb6bd2e-f952-4f2a-846c-e7023c3c6e0f.png">
<img width="740" alt="image" src="https://user-images.githubusercontent.com/97814802/157656894-a98d3ab2-1813-48dc-80e7-ddf0ca3aa20c.png">
