### ISSUE TITLE
Account number text in bank transfer modal for giving shows up in the wrong line

### ISSUE THREAD

**Issue by ksuhartono97** [hmcc-global/hmcchk-web#301]
![WhatsApp Image 2022-03-18 at 2 17 26 PM](https://user-images.githubusercontent.com/16095743/159144439-ca927b9e-479b-4524-b905-85a81ab5e678.jpeg)

Account number should appear in a new line

**Comment by tamarayustian** [comment]
hi, i got the message that the account number is missing a 0 at the beginning, so it should be Account Number: *0*13012090
