### ISSUE TITLE
The Simple Gospel should be reclassified as individual TSG's (controversial issues, free at last, etc) instead of being under TSG blanket

### ISSUE THREAD

**Issue by ksuhartono97** [hmcc-global/hmcchk-web#303]
![WhatsApp Image 2022-03-19 at 12 52 45 PM (1)](https://user-images.githubusercontent.com/16095743/159144516-bafc09b3-52fb-4605-8632-5e376c270fa3.jpeg)

Not sure if this is our responsibility or MM responsibility, but should take care of communicating and fixing this? People keep asking us abt this lol

**Comment by bhryck** [comment]
communicate to MM that they should do this, hopefully dont have to do this manually. form a protocol
