### ISSUE TITLE
IG Embed

### ISSUE THREAD

**Issue by albertparedandan** [hmcc-global/hmcchk-web#308]

**Comment by albertparedandan** [comment]
![Screenshot 2022-03-23 at 23 13 25](https://user-images.githubusercontent.com/33679483/159732349-1089c71b-e559-4256-a5b0-a28264b446af.png)

**Comment by albertparedandan** [comment]
Deploy by 1 April, Friday

**Comment by albertparedandan** [comment]
Figure out a way to change embed link every 6 days, ideally without re-deploying. Talk to Malvin about getting the embed link and flow for it

**Comment by albertparedandan** [comment]
@kmalvin to show what the modal will look like when visiting this page during GF/Easter weekend

**Comment by bhryck** [comment]
header: center aligned
title size: 22px
pagination: load more
free trial is for 7 days


<div class="embedsocial-hashtag" data-ref="53b27a9390cbc945fc10174a67bec1b831b8b6ef"></div><script>(function(d, s, id){var js; if (d.getElementById(id)) {return;} js = d.createElement(s); js.id = id; js.src = "https://embedsocial.com/cdn/ht.js"; d.getElementsByTagName("head")[0].appendChild(js);}(document, "script", "EmbedSocialHashtagScript"));</script>

**Comment by bhryck** [comment]
header: center aligned
title size: 22px
pagination: load more
free trial is for 7 days

<div class="embedsocial-hashtag" data-ref="53b27a9390cbc945fc10174a67bec1b831b8b6ef"></div><script>(function(d, s, id){var js; if (d.getElementById(id)) {return;} js = d.createElement(s); js.id = id; js.src = "https://embedsocial.com/cdn/ht.js"; d.getElementsByTagName("head")[0].appendChild(js);}(document, "script", "EmbedSocialHashtagScript"));</script>

**Comment by kmalvin** [comment]
> 


![Screen Shot 2022-03-26 at 14 34 23](https://user-images.githubusercontent.com/44461134/160227881-b7c3e53e-3e16-482f-ba4c-66264cd4f932.png)
![Screen Shot 2022-03-26 at 14 34 39](https://user-images.githubusercontent.com/44461134/160227890-2df354f2-5b97-4d79-9666-9844302f94da.png)

here's the modal within gf/easter invite page that will be more explicit to direct people into the streaming homepage. designed for different colors, depending if we're 'welcoming' GF or Easter. lmk what u guys think.

**Comment by albertparedandan** [comment]
for mobile, just stick to the already coded behaviour. refer to: https://github.com/hmcc-global/hmcchk-web/blob/main/ui/src/components/sermons/UpcomingSermon.js

**Comment by bhryck** [comment]
![image](https://user-images.githubusercontent.com/24607458/160235375-3924298a-caf9-4412-8621-d78abe248f42.png)

copy pasting the socialembed code seems to work so lets stick to this. dont think theres a way to automate switching free accounts for  this since the link has to be generated beforehand and is only active for 7 days after generation

**Comment by bhryck** [comment]
![image](https://user-images.githubusercontent.com/24607458/160417714-b544a14e-1089-43e1-9a96-ef782dfb2e6c.png)
facing issues trying to query a bitly link using axios.get. think its caused by the server config not allowing redirects of other websites. any advice to get around this?

**Comment by albertparedandan** [comment]
ig emebd done, modal not done -> to finish this coming week
