### ISSUE TITLE
GF Streaming page

### ISSUE THREAD

**Issue by albertparedandan** [hmcc-global/hmcchk-web#312]
Very related to #311 . Just have to change background, text colour

**Comment by albertparedandan** [comment]
![Screenshot 2022-03-23 at 23 39 44](https://user-images.githubusercontent.com/33679483/159738044-bdf9da93-872b-473b-8842-8713439bd032.png)

**Comment by albertparedandan** [comment]
aiming to finish by this coming week

**Comment by albertparedandan** [comment]
done, link to response form still pending

**Comment by albertparedandan** [comment]
change response button behaviour to show modal for response instructions

**Comment by kmalvin** [comment]
modal design and details final design:
<img width="693" alt="Screen Shot 2022-04-06 at 22 40 58" src="https://user-images.githubusercontent.com/44461134/162000912-7ca73b4d-da42-4413-a666-5720917e2609.png">

please note the difference in design between desktop and mobile versions.
desktop: has images.
mobile: no images, and has the 'notice' line to entice people to move over to desktop

lmk if this is not possible?

better quality images (if cannot be obtained from figma), can be retrieved here: https://docs.google.com/document/d/e/2PACX-1vSfUXFmCHv4lCzx69nlnVRkMIey87uHeROqpmxmVnsq_MfenomRdiaXXd8TZ70aNB0wWiz_RPRzdkZy/pub
