### ISSUE TITLE
pop-up-modal

### ISSUE THREAD

**Issue by samyakobus** [hmcc-global/hmcchk-web#344]
![image](https://user-images.githubusercontent.com/33675629/162501075-224993e9-c836-4db1-a74a-0e46541630f7.png)

![image](https://user-images.githubusercontent.com/33675629/162501106-f1d4ba21-5c85-43be-97d7-92df63053564.png)

here's the modal within gf/easter invite page that will be more explicit to direct people into the streaming homepage. designed for different colors, depending if we're 'welcoming' GF or Easter. lmk what u guys think.

for mobile, just stick to the already coded behaviour. refer to: https://github.com/hmcc-global/hmcchk-web/blob/main/ui/src/components/sermons/UpcomingSermon.js

**Comment by bhryck** [comment]
can check on "text align issue" commit to see how to center the LIVE text

**Comment by bhryck** [comment]
![image](https://user-images.githubusercontent.com/24607458/162568152-f0514406-810e-4c74-a59d-2476a10498f0.png)
`  <Box
        position="absolute"
        right="25px"
        top="10px"
        height="auto"
        maxW="85%"
        width={{ base: 'none', md: '200' }}
        background="#FFFFFF"
        boxShadow="0px 3px 4px 2px rgba(0, 0, 0, 0.3)"
        borderRadius="20px"
        display={{ base: 'none', md: displayModal }}
        px={[2, 4]}
        py={[2, 4]}
        zIndex="sticky"
      >`
the modal should be below the navbar so the links dont get blocked. also try using em instead of px for it should be more consistent accross devices
