### ISSUE TITLE
Bigger verse image for Desktop because it's hard to read right now

### ISSUE THREAD

**Issue by tamarayustian** [hmcc-global/hmcchk-web#353]
- Can we make the verse image bigger for the desktop? it's a bit hard to read right now

**Comment by tamarayustian** [comment]
![Screenshot 2022-04-23 at 3 03 32 AM](https://user-images.githubusercontent.com/26876443/163034881-154df808-ca6c-41a3-b16a-ebf19c6c48e6.png)

**Comment by albertparedandan** [comment]
done ish? cant be bigger since underlying image is small
