### ISSUE TITLE
Make example clearer for Easter response form

### ISSUE THREAD

**Issue by tamarayustian** [hmcc-global/hmcchk-web#354]
in the example for fill in the blank in easter response time, can the example answer also have underline? so it’s like this: "Because _God is loving_, I commit to _sharing God's love with others_ in _my workplace_.”

**Comment by tamarayustian** [comment]
![Screenshot 2022-04-23 at 3 01 28 AM](https://user-images.githubusercontent.com/26876443/163034994-29adb6e6-a93e-456f-99a0-2699d22047fc.png)

**Comment by albertparedandan** [comment]
done
