### ISSUE TITLE
Clearer instructions on verse image in Easter response form

### ISSUE THREAD

**Issue by tamarayustian** [hmcc-global/hmcchk-web#357]
- Can we add a note on how people can save like drag & drop or right click to save? similar to invitation in easter page

On mobile: "Press-and-hold this image to save and set it as your wallpaper as a personal reminder!"
On desktop: "Right-click and save this image to set it as your wallpaper as a personal reminder!"

**Comment by tamarayustian** [comment]
![Screenshot 2022-04-23 at 3 03 32 AM](https://user-images.githubusercontent.com/26876443/163146233-afaa1348-0b68-41de-a4de-af7bd0cb4263.png)

**Comment by albertparedandan** [comment]
done
