### ISSUE TITLE
In-Person: Changing Home Page

### ISSUE THREAD

**Issue by samyakobus** [hmcc-global/hmcchk-web#370]
![image](https://user-images.githubusercontent.com/33675629/163751015-93cdbe0f-cd3c-4334-9385-4676b38aab7f.png)

1) COVID-19 Policy
2) "ONLINE ONLY"
3) Easter Highlight (Maybe)

<img width="749" alt="Screen Shot 2022-04-18 at 23 29 35" src="https://user-images.githubusercontent.com/44461134/163831906-1963f9cc-8746-47b7-927e-14d91f41cc94.png">

4) On-load modal ("I'm new")

**Comment by kmalvin** [comment]
For number 1, CXO might be looking at a not so subtle changes, potentially introducing 3 buttons instead. Will finalize and revert with the design (minor) and expected behavior.

**Comment by kmalvin** [comment]
For number 2, please change it to

> Sunday Celebration: 10AM HKT In-person & Online

**Comment by kmalvin** [comment]
For number 3 (feature image), please change it to our newest _**welcome home**_ ad:
![welcome home - ad 1320_800](https://user-images.githubusercontent.com/44461134/163830823-b84f6584-99c3-4f8b-9da5-d076b9ef9c94.png)

If the images are broken when downloading here, please download them directly from our HMCC shared drive: https://drive.google.com/drive/folders/1ihOCrf8dF4DfKTEA1mywQ_G-KZl_tqx5 

and download the image titled:
> welcome home - ad 1320_800.png

**Comment by kmalvin** [comment]
For number 4, the _**Welcome! Are you new?**_ modal that appears each time user accesses our website (https://hongkong.hmcc.net) should be updated to look as such:

Web
<img width="832" alt="Screen Shot 2022-04-18 at 23 50 42" src="https://user-images.githubusercontent.com/44461134/163834962-b9d6dc56-e4c5-4dc7-bf17-f9a74161ae69

Mobile
<img width="456" alt="Screen Shot 2022-04-18 at 23 51 36" src="https://user-images.githubusercontent.com/44461134/163835077-97e7ad9d-ab47-4ea3-a9d3-50b3808fcb6e.png">
.png">

[Figma file reference: https://www.figma.com/file/unLVEyKxqww3mOeLNNaoQJ/%5BCRTVS%5D-hongkong.HMCC.net-Revamp?node-id=3826%3A15583 ; WELCOME HOME homepage page]
