### ISSUE TITLE
In-Person: Visit Page

### ISSUE THREAD

**Issue by samyakobus** [hmcc-global/hmcchk-web#371]
For the Invitation Part:
![image](https://user-images.githubusercontent.com/33675629/163751898-f5885631-e85e-4179-923b-4bc8b01895d0.png)

FAQ:
![image](https://user-images.githubusercontent.com/33675629/163752092-42a66d52-4418-46c5-9760-84d5870e754b.png)

**Comment by Tourplant** [comment]
In FAQs: (correspond to the red boxes in the pic above)
1. Can delete 
2. Can delete
3. Can delete
4. Can delete
5. Changed to: Therefore, we are now meeting in person and streaming church online as well...Please refer to our COVID-19 policy [here].

**Comment by kmalvin** [comment]
For the invitation part mentioned by SamYak above, please revert it to original design of the page, that would something like:
![image](https://user-images.githubusercontent.com/44461134/163829738-f8737823-4c84-4e33-837f-3b086ee0dbe2.png)

please follow the wordings within the image! :)
