### ISSUE TITLE
Paid Events Forms

### ISSUE THREAD

**Issue by yuenyauu** [hmcc-global/hmcchk-web#606]

**Comment by andreajeka** [comment]
- [ ] Add flag on form editor, eg. is this a paid event?
- [ ] Add indicator on user profile whether a form is paid or non-paid
- [ ] Add filter paid or non-paid on forms admin page (eg. tab or toggle)
- [ ] Apply different permissions to paid or non-paid page. (eg. paid = admin + stewardship)
