### ISSUE TITLE
Scroll down behavior on navigating between sections

### ISSUE THREAD

**Issue by ksuhartono97** [hmcc-global/hmcchk-web#875]
currently, clicking the links change the section but doesn't do a scroll down behavior to reveal the content. might be confusing to the users since hero section is full screen but they don't see anything happen when they click links.

should scroll down to reveal content when we navigate to sections

![Image](https://github.com/hmcc-global/hmcchk-web/assets/16095743/64f3340e-3c10-4ca8-9b75-aeeca6436937)

**Comment by tamarayustian** [comment]
decided to make banner shorter, as per discussion with CXO
