### ISSUE TITLE
The Story page is "floating"

### ISSUE THREAD

**Issue by cornyachtsorry** [hmcc-global/hmcchk-web#879]
Not sure why I can scroll the page left and right. 
When I want to swipe the story part, it feels "slippery" as shown in the picture below

![image](https://github.com/hmcc-global/hmcchk-web/assets/8019899/dab57e4c-bfc9-4097-a864-7d0b97726d9d)

**Comment by yuenyauu** [comment]
doesn't scroll left and right for me.. (OnePlus 9 pro)

**Comment by Midnite1212** [comment]
tried other dimensions too, it worked fine ?..
