### ISSUE TITLE
ROC The Space Fixes

### ISSUE THREAD

**Issue by melissaprayogo** [hmcc-global/hmcchk-web#884]
make it the same size as the 'crocodile centre' circle.
![IMG_4995](https://github.com/hmcc-global/hmcchk-web/assets/100053797/173e9360-9272-4bae-a439-44fca98fcd5e)

**Comment by yuenyauu** [comment]
![image](https://github.com/hmcc-global/hmcchk-web/assets/66002742/a96c0727-f91c-4527-b620-b77175866e64)
- make Crocodile Centre larger
